version: 2
jobs:
  build:
    docker:
      - image: circleci/<language>:<version TAG>
    steps:
      - checkout
      - run: echo "Hello World!"
  test:
    docker:
      - image: circleci/<language>:<version TAG>
    steps:
      - checkout
      - run: echo "Test Has Run!"
